/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourceRouteImport } from './routes/source'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersSlugRouteImport } from './routes/players.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/inbox': typeof InboxRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/sources': typeof SourcesRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/inbox': typeof InboxRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/sources': typeof SourcesRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/inbox': typeof InboxRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/sources': typeof SourcesRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/corrections'
    | '/inbox'
    | '/robots.txt'
    | '/saved'
    | '/sitemap.xml'
    | '/source'
    | '/sources'
    | '/articles/$id'
    | '/players/$slug'
    | '/articles/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/corrections'
    | '/inbox'
    | '/robots.txt'
    | '/saved'
    | '/sitemap.xml'
    | '/source'
    | '/sources'
    | '/articles/$id'
    | '/players/$slug'
    | '/articles'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/corrections'
    | '/inbox'
    | '/robots.txt'
    | '/saved'
    | '/sitemap.xml'
    | '/source'
    | '/sources'
    | '/articles/$id'
    | '/players/$slug'
    | '/articles/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CorrectionsRoute: typeof CorrectionsRoute
  InboxRoute: typeof InboxRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourceRoute: typeof SourceRoute
  SourcesRoute: typeof SourcesRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CorrectionsRoute: CorrectionsRoute,
  InboxRoute: InboxRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourceRoute: SourceRoute,
  SourcesRoute: SourcesRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  PlayersSlugRoute: PlayersSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
